name: tests-films

on:
  pull_request:
    paths:
      - 'films/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd films && npm install && npm run test:ci
