name: tests-auth

on:
  pull_request:
    paths:
      - 'auth/**'

jobs:
  build: # Run a virutal machine
    runs-on: ubuntu-latest # Running ubuntu at the latest version
    steps: # To do in the virtual machine
      - uses: actions/checkout@v2 # Take all the code out of the project
      - run: cd auth && npm install && npm run test:ci # Command to run all the tests only in the auth service
